---
abstract: 'rotate input stream into pieces automatically'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Exporter: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  IO::Dir: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Rolling
provides:
  App::Rolling:
    file: lib/App/Rolling.pm
    version: 0.10
requires:
  Carp: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Interactive: 0
  Path::Class: 0
  Pod::Usage: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/App-Rolling
version: 0.10
